### PR TITLE
Allow choosing different offset policies

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
@bouskaJ are you able to try this one and see if it works?

**Comment by bouskaJ** [comment]
@orpiske Could ou add your use-case to https://github.com/citrusframework/yaks/blob/master/java/steps/yaks-kafka/src/test/resources/org/citrusframework/yaks/kafka/kafka.feature ?

**Comment by orpiske** [comment]
Let's hold this one for a while. I got a test from @bouskaJ and the code is not working as I'd expect (it's causing a timeout). I'll investigate this.

**Comment by christophd** [comment]
@orpiske maybe close the PR and open once you are set?

**Comment by orpiske** [comment]
@christophd yeah, let's close this one for now. I had to focus on something else and couldn't follow up with this. I'll reopen after I debug it completely. Thanks!

**Pull request closed without merging**
