### PR TITLE
Add initial e2e-test for examples

### PR DESCRIPTION
**Pull request by nicolaferraro**
This is using kind + camel k actions (we may add a yaks action as well, for other repos).

### CODE REVIEW

**Comment by nicolaferraro** [comment]
Will figure out why they don't start....

**Comment by christophd** [comment]
@nicolaferraro is this still a WIP? Looks good to me right now

**Comment by christophd** [comment]
This is so awesome BTW 👍

**Comment by nicolaferraro** [comment]
> This is so awesome BTW

Yeah, we can merge it and increment test coverage later

**Pull request merged**
